name: container-image

on:
  push:
    tags:
      - "**"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for hotfix release
        id: check-hotfix
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+\+hotfix\.[0-9]+$ ]]; then
              echo "release-type=hotfix" >> $GITHUB_OUTPUT
          fi

      - name: Set Docker metadata (standard)
        if: steps.check-hotfix.outputs.release-type != 'hotfix'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            test1
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value={{date 'YYYYMMDD.HHmmss'}}-{{sha}}
            type=match,pattern=v(\d.\d.\d\+hotfix\.\d)
            type=match,pattern=v(\d.\d.\d\hotfix.\d)

      - name: Set Docker metadata (hotfix)
        if: steps.check-hotfix.outputs.release-type == 'hotfix'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            test1
          flavor: |
            latest=false
          tags: |
            type=match,pattern=v(\d+\.\d+\.\d+\+hotfix\.\d+),group=1
