name: Check image

on:
  workflow_dispatch:
    inputs:
      image:
        description: The image with optional tag to check

jobs:
  check-image:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: docker manifest
        run: docker manifest inspect ${{ github.event.inputs.image }}
