name: Trigger Repository Dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - testing
          - staging
          - production
        description: The environment to be updated
        required: true
      image_tag:
        description: The container image tag to set
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: rswrz/test1
          event-type: update-image-tags
          client-payload: '{"image_tag": "${{ github.event.inputs.image_tag }}", "environment": "${{ github.event.inputs.environment }}"}'
