name: hotfix-release

on:
  push:
    branches:
      - hotfix/*

jobs:
  hotfix-release:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - name: tag hotfix
        id: hotfix
        run: |
          release_version=${GITHUB_REF_NAME##*/}
          latest_existing_hotfix_version=$(git tag -l "${release_version}+hotfix.*" --sort='-version:refname' | head -n1 | rev | cut -d. -f1 | rev)
          if [ -n "$latest_existing_hotfix_version" ]; then
            hotfix_version=$latest_existing_hotfix_version
          else
            hotfix_version=0
          fi

          tag=${release_version}+hotfix.${hotfix_version}"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${tag}"
          git push origin "${tag}"
