name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          create-summary: true
          github-token: ${{ null }}
          output-file: false
          pre-release-identifier: alpha
          pre-release: true
          skip-commit: true
          skip-on-empty: false
