name: release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          create-summary: true
          github-token: ${{ null }}
          skip-version-file: true
          skip-ci: false
