name: release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - name: Tag commit with semantic version
        uses: TriPSs/conventional-changelog-action@v3
        with:
          create-summary: true
          # Disable GITHUB_TOKEN authentication to be able
          # to use deploy key defined in `ssh-key` in actions/checkout
          github-token: ${{ null }}
          skip-ci: false
          skip-version-file: true
