name: release

on:
  push:
    branches:
      - release
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          create-summary: true
          git-branch: main
          github-token: ${{ null }}
          skip-on-empty: false
          skip-version-file: true

      - name: Delete release branch
        run: git push --delete origin ${{ github.ref_name }}
