name: release

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      stage:
        default: alpha
        description: Which stage to release
        options:
          - alpha
          - beta
          - rc
          - release
        required: true
        type: choice
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}
      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          create-summary: true
          github-token: ${{ null }}
          output-file: false
          pre-release: true
          pre-release-identifier: ${{ github.event.inputs.stage }}
          skip-commit: true
          skip-on-empty: false
