name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - run: git remote -v
      - run: git commit --allow-empty -m 'Empty commit'
      - run: git push

      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
