name: release2

on: workflow_dispatch

jobs:
  release2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - name: Generate changelog
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        with:
          github-token:
          create-summary: true
          output-file: false
          skip-commit: true
          skip-on-empty: false

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
